import React from 'react';
import Head from 'next/head'
import Link from 'next/link'
import styles from './styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WeNeedLove</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          WeNeedLove
        </h1>

        <span className={styles.description_2}>
          you are a good person never forget it
        </span>
        
        <span className={styles.description}>
          Love is Everywhere
        </span>

        <div className={styles.grid}>
          <Link href="/need-love">
            <a className={`${styles.card} ${styles.need_love}`} title='Need love'></a>
          </Link>

          <Link href="/give-love">
            <a className={`${styles.card} ${styles.give_love}`} title='give love'></a>
          </Link>
        </div>

        <a href="https://nextjs.org/docs" className={`${styles.card} ${styles.my_love}`} title='my love'>
          </a>

      </main>
    </div>
  )
}
